<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.*" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.*" />
    <ProjectReference Include="../OpenDockify.Generation/OpenDockify.Generation.csproj" />
    <ProjectReference Include="../OpenDockify.Templates/OpenDockify.Templates.csproj" />
    <PackageReference Include="Platform.Jobs" Version="0.1.0" />
  </ItemGroup>
</Project>
