<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.*" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenDockify.Esign\OpenDockify.Esign.csproj" />
    <ProjectReference Include="..\OpenDockify.Templates\OpenDockify.Templates.csproj" />
    <ProjectReference Include="..\OpenDockify.Finance\OpenDockify.Finance.csproj" />
    <ProjectReference Include="..\OpenDockify.Rendering\OpenDockify.Rendering.csproj" />
    <ProjectReference Include="..\OpenDockify.SystemConfig\OpenDockify.SystemConfig.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Platform.Caching" Version="0.1.0" />
    <PackageReference Include="Platform.Storage" Version="0.1.0" />
  </ItemGroup>

</Project>
