<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\OpenDockify.Data\OpenDockify.Data.csproj" />
    <ProjectReference Include="..\OpenDockify.Operations\OpenDockify.Operations.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Platform.Persistence.EfCore.Migrator" Version="0.1.0" />
    <PackageReference Include="Platform.Storage" Version="0.1.0" />
    <PackageReference Include="Platform.Storage.Local" Version="0.1.0" />
  </ItemGroup>
</Project>
